config/routes.rb
Rails.application.routes.draw do
  get 'pets/index'
  get 'pets/show'
  devise_for :users
  get 'home/index'
  root 'home#index'
  get 'home/about'
  get 'home/contact'
  get 'home/adopter'
  get 'home/soutenir'

  get "up" => "rails/health#show", as: :rails_health_check

  # Routes pour les différentes espèces
  resources :dogs, only: [:index, :show]
  resources :cats, only: [:index, :show]
  resources :fishes, only: [:index]
  resources :reptiles, only: [:index]
  resources :horses, only: [:index]
  resources :birds, only: [:index]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/models/dog.rb
# app/models/dog.rb
class Dog < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true
  validates :species, presence: true
  validates :breed, presence: true
  validates :sex, presence: true
  validates :sterilized, inclusion: { in: [true, false] }
  validates :photo, presence: true
end

app/models/pet.rb
# app/models/pet.rb

class Pet < ApplicationRecord
  validates :name, :age, :species, :breed, :sex, :sterilized, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/birds_controller.rb
class BirdsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
  end
end

app/controllers/fishes_controller.rb
class FishesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def soutenir
  end

  def adopter
  end

end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/reptiles_controller.rb
class ReptilesController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birds_helper.rb
module BirdsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/fishes_helper.rb
module FishesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/horses_helper.rb
module HorsesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/reptiles_helper.rb
module ReptilesHelper
end

app/views/birds/index.html.erb
<!-- app/views/birds/index.html.erb -->
<div class="container mt-5">
  <h1 class="text-center text-success my-5">Oiseaux Disponibles à l'Adoption</h1>
  <p class="no-availability-message">Pas d'oiseaux disponibles</p>
</div>

app/views/birds/show.html.erb
<h1>Birds#show</h1>
<p>Find me in app/views/birds/show.html.erb</p>

app/views/cats/index.html.erb
<!-- app/views/cats/index.html.erb -->
<h1 class="text-center text-success my-5">Chats Disponibles à l'Adoption</h1>

<div class="container">
  <div class="row">
    <% @cats.each do |cat| %>
      <div class="col-md-4 mb-4">
        <div class="card h-100">
          <%= image_tag(cat.photo, alt: cat.name, class: 'card-img-top img-thumbnail') %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to cat.name, cat_path(cat) %></h5>
            <p class="card-text">Âge: <%= cat.age %> ans</p>
            <p class="card-text">Race: <%= cat.breed %></p>
            <p class="card-text">Sexe: <%= cat.sex %></p>
            <p class="card-text">Stérilisé: <%= cat.sterilized ? 'Oui' : 'Non' %></p>
            <p class="card-text">Remarques: <%= cat.remarks %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cats/show.html.erb
<!-- app/views/cats/show.html.erb -->
<h1><%= @cat.name %></h1>
<p>Âge: <%= @cat.age %></p>
<p>Race: <%= @cat.breed %></p>
<p>Sexe: <%= @cat.sex %></p>
<p>Stérilisé: <%= @cat.sterilized ? 'Oui' : 'Non' %></p>
<p>Remarques: <%= @cat.remarks %></p>

app/views/dogs/index.html.erb
<!-- app/views/dogs/index.html.erb -->
<h1 class="text-center text-success my-5">Chiens Disponibles à l'Adoption</h1>

<div class="container">
  <div class="row">
    <% @dogs.each do |dog| %>
      <div class="col-md-4 mb-4">
        <div class="card h-100">
          <%= image_tag(dog.photo, alt: dog.name, class: 'card-img-top') %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to dog.name, dog_path(dog) %></h5>
            <p class="card-text">Âge: <%= dog.age %> ans</p>
            <p class="card-text">Race: <%= dog.breed %></p>
            <p class="card-text">Sexe: <%= dog.sex %></p>
            <p class="card-text">Stérilisé: <%= dog.sterilized ? 'Oui' : 'Non' %></p>
            <p class="card-text">Remarques: <%= dog.remarks %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dogs/show.html.erb
<!-- app/views/dogs/show.html.erb -->
<h1><%= @dog.name %></h1>
<p>Âge: <%= @dog.age %></p>
<p>Race: <%= @dog.breed %></p>
<p>Sexe: <%= @dog.sex %></p>
<p>Stérilisé: <%= @dog.sterilized ? 'Oui' : 'Non' %></p>
<p>Remarques: <%= @dog.remarks %></p>

app/views/fishes/index.html.erb
<!-- app/views/fishes/index.html.erb -->
<div class="container mt-5">
  <h1 class="text-center text-success my-5">Poissons Disponibles à l'Adoption</h1>
  <p class="no-availability-message">Pas de poissons disponibles</p>
</div>

app/views/fishes/show.html.erb
<h1>Fishes#show</h1>
<p>Find me in app/views/fishes/show.html.erb</p>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container">
    <%= link_to 'AnimauxCherchentMaison.com', root_path, class: "navbar-brand text-white" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%= link_to 'Accueil', home_index_path, class: "nav-link" %>
        <%= link_to 'À propos', home_about_path, class: "nav-link" %>
        <%= link_to 'Contact', home_contact_path, class: "nav-link" %>
        <%= link_to 'Soutenir', home_soutenir_path, class: "nav-link" %>
        <%= link_to 'À adopter', home_adopter_path, class: "nav-link" %>
      </ul>

      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <%= link_to 'Mon Profil', edit_user_registration_path, class: "nav-link" %>
          <%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to 'Se connecter', new_user_session_path, class: "nav-link" %>
          <%= link_to 'S\'inscrire', new_user_registration_path, class: "nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-12 text-center">
      <h1 class="display-4"><span class="text-success">AnimauxCherchentMaison.com</span></h1>
      <p class="lead">Notre mission : Trouver des foyers aimants pour chaque animal</p>
      <hr class="my-4">
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-md-6 d-flex flex-column justify-content-center">
      <div class="bubble">
        <h2 class="mb-4">Notre Histoire</h2>
        <p>
          AnimauxCherchentMaison.com est né de la passion et du dévouement de notre équipe envers le bien-être animal.
          Nous avons constaté un besoin croissant de relier les animaux sans foyer avec des familles aimantes, et c'est ainsi que notre plateforme a vu le jour.
          Depuis notre lancement, nous avons aidé des milliers d'animaux à trouver une nouvelle maison et continuons de travailler pour en aider encore plus.
        </p>
      </div>
    </div>
    <div class="col-md-6">
      <%= image_tag 'chien1.jpg', alt: 'Animaux heureux', class: 'img-fluid rounded shadow-lg-custom' %>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-md-6 order-md-2 d-flex flex-column justify-content-center">
      <div class="bubble">
        <h2 class="mb-4">Notre Équipe</h2>
        <p>
          Derrière AnimauxCherchentMaison.com se trouve une équipe de professionnels et de bénévoles passionnés par les animaux.
          Notre équipe est composée de vétérinaires, de dresseurs, de spécialistes en comportement animal, et de développeurs web travaillant ensemble pour offrir la meilleure expérience possible aux utilisateurs et aux animaux.
          Nous croyons fermement que chaque animal mérite une chance de trouver un foyer aimant.
        </p>
      </div>
    </div>
    <div class="col-md-6 order-md-1">
      <%= image_tag 'chien3.jpg', alt: 'Équipe', class: 'img-fluid rounded shadow-lg-custom' %>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-md-6 d-flex flex-column justify-content-center">
      <div class="bubble">
        <h2 class="mb-4">Comment ça Marche</h2>
        <p>
          Notre plateforme est simple et intuitive. Les utilisateurs peuvent parcourir les profils des animaux disponibles, filtrer par type, âge, taille, et autres critères pour trouver l'animal qui correspond le mieux à leur foyer.
          Une fois qu'un animal est sélectionné, il suffit de remplir une demande d'adoption en ligne. Notre équipe et les refuges partenaires examinent chaque demande pour assurer que chaque adoption soit un succès.
        </p>
      </div>
    </div>
    <div class="col-md-6">
      <%= image_tag 'chien2.jpg', alt: 'Processus d\'adoption', class: 'img-fluid rounded shadow-lg-custom' %>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-md-12 text-center">
      <div class="bubble">
        <h2 class="mb-4">Impliquez-vous</h2>
        <p>
          Il existe plusieurs façons de s'impliquer avec AnimauxCherchentMaison.com. En plus de l'adoption, vous pouvez devenir bénévole, faire un don pour soutenir notre mission, ou même simplement partager notre site avec vos amis et votre famille.
          Chaque geste compte et aide à offrir une nouvelle vie à un animal dans le besoin.
        </p>
        <%= link_to 'En savoir plus', '#', class: 'btn btn-success btn-lg' %>
      </div>
    </div>
  </div>
</div>

app/views/home/adopter.html.erb
<div class="container mt-5">
  <h1 class="text-center mb-4 title-custom text-success">Adopter un Animal</h1>
  <div class="row">
    <div class="col-md-4 text-center mb-4">
      <%= link_to dogs_path do %>
        <div class="card">
          <%= image_tag 'dogs.webp', alt: 'Chiens', class: 'card-img-top img-thumbnail mx-auto d-block' %>
          <div class="card-body">
            <h5 class="card-title text-success">Chiens</h5>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4 text-center mb-4">
      <%= link_to cats_path do %>
        <div class="card">
          <%= image_tag 'cats.webp', alt: 'Chats', class: 'card-img-top img-thumbnail mx-auto d-block' %>
          <div class="card-body">
            <h5 class="card-title text-success">Chats</h5>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4 text-center mb-4">
      <%= link_to fishes_path do %>
        <div class="card">
          <%= image_tag 'fishes.webp', alt: 'Poissons', class: 'card-img-top img-thumbnail mx-auto d-block' %>
          <div class="card-body">
            <h5 class="card-title text-success">Poissons</h5>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-md-4 text-center mb-4">
      <%= link_to reptiles_path do %>
        <div class="card">
          <%= image_tag 'reptiles.webp', alt: 'Reptiles', class: 'card-img-top img-thumbnail mx-auto d-block' %>
          <div class="card-body">
            <h5 class="card-title text-success">Reptiles</h5>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4 text-center mb-4">
      <%= link_to horses_path do %>
        <div class="card">
          <%= image_tag 'horses.webp', alt: 'Chevaux', class: 'card-img-top img-thumbnail mx-auto d-block' %>
          <div class="card-body">
            <h5 class="card-title text-success">Chevaux</h5>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4 text-center mb-4">
      <%= link_to birds_path do %>
        <div class="card">
          <%= image_tag 'birds.webp', alt: 'Oiseaux', class: 'card-img-top img-thumbnail mx-auto d-block' %>
          <div class="card-body">
            <h5 class="card-title text-success">Oiseaux</h5>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/contact.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="bubble"> <!-- Ajout de la classe bubble ici -->
        <h1 class="text-center text-success-custom">Contactez-nous</h1> <!-- Texte en vert -->
        <p class="text-center">Nous serions ravis de vous entendre. Veuillez remplir le formulaire ci-dessous pour nous contacter.</p>

        <form>
          <div class="mb-3">
            <label for="name" class="form-label">Nom</label>
            <input type="text" class="form-control" id="name" placeholder="Votre nom">
          </div>
          <div class="mb-3">
            <label for="email" class="form-label">Adresse email</label>
            <input type="email" class="form-control" id="email" placeholder="Votre adresse email">
          </div>
          <div class="mb-3">
            <label for="message" class="form-label">Message</label>
            <textarea class="form-control" id="message" rows="5" placeholder="Votre message"></textarea>
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-success">Envoyer</button> <!-- Bouton en vert -->
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<!-- Mini Carrousel -->
<div class="carousel-container mt-4 mx-auto" style="max-width: 250px;">
  <div id="animalCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag 'rex.webp', class: 'd-block w-100', alt: 'Rex' %>
      </div>
      <div class="carousel-item">
        <%= image_tag 'bella.webp', class: 'd-block w-100', alt: 'Bella' %>
      </div>
      <!-- Ajoutez d'autres images ici -->
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#animalCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#animalCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

<div class="jumbotron bg-success text-white mt-4 p-4">
  <div class="container text-center welcome-bubble">
    <h1 class="display-4">Bienvenue sur Animaux Cherchent Maison</h1>
    <p class="lead">Un site dédié à trouver des foyers aimants pour les animaux sans abri.</p>
    <hr class="my-4">
    <p>Rejoignez-nous et aidez à faire une différence dans la vie des animaux.</p>
    <a class="btn btn-light btn-lg me-2" href="<%= home_adopter_path %>" role="button">Adopter</a>
    <a class="btn btn-light btn-lg" href="<%= home_soutenir_path %>" role="button">Soutenir</a>
  </div>
</div>

<div class="container mt-4">
  <div class="row">
    <div class="col-md-4 text-center">
      <h2>Adopter</h2>
      <p>Découvrez des animaux adorables qui cherchent un foyer. Adoptez un animal de compagnie aujourd'hui et faites une différence.</p>
      <%= link_to 'Voir les animaux à adopter', home_adopter_path, class: 'btn btn-success' %>
    </div>
    <div class="col-md-4 text-center">
      <h2>Soutenir</h2>
      <p>Apprenez comment vous pouvez soutenir notre mission. Devenez bénévole ou faites un don pour aider les animaux dans le besoin.</p>
      <%= link_to 'En savoir plus', home_soutenir_path, class: 'btn btn-success' %>
    </div>
    <div class="col-md-4 text-center">
      <h2>Contact</h2>
      <p>Avez-vous des questions ou souhaitez-vous en savoir plus sur notre organisation ? Contactez-nous dès aujourd'hui.</p>
      <%= link_to 'Nous contacter', home_contact_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/home/soutenir.html.erb
<!-- app/views/home/soutenir.html.erb -->

<div class="container mt-5">
  <div class="row">
    <div class="col-md-12 text-center">
      <h1 class="display-4 text-success">Soutenir AnimauxCherchentMaison.com</h1>
      <p class="lead">Chaque geste compte pour offrir une nouvelle vie aux animaux dans le besoin.</p>
      <hr class="my-4">
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-md-4 text-center">
      <div class="card h-100">
        <%= image_tag 'VIER_PFOTEN.webp', alt: 'Bénévolat', class: 'card-img-top' %>
        <div class="card-body">
          <h5 class="card-title">Devenir Bénévole</h5>
          <p class="card-text">
            Rejoignez notre équipe de bénévoles passionnés et aidez-nous à offrir une seconde chance aux animaux. Chaque minute de votre temps est précieuse.
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-4 text-center">
      <div class="card h-100">
        <%= image_tag 'donation-immobiliere.jpg', alt: 'Donations', class: 'card-img-top' %>
        <div class="card-body">
          <h5 class="card-title">Faire un Don</h5>
          <p class="card-text">
            Vos dons nous permettent de fournir des soins médicaux, de la nourriture, et un abri aux animaux dans le besoin. Chaque contribution fait une différence.
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-4 text-center">
      <div class="card h-100">
        <%= image_tag 'triste.jpg', alt: 'Partager', class: 'card-img-top' %>
        <div class="card-body">
          <h5 class="card-title">Partager</h5>
          <p class="card-text">
            Aidez-nous à sensibiliser le public en partageant notre mission avec vos amis et votre famille. Plus nous sommes nombreux, plus nous pouvons aider d'animaux.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-5">
    <div class="col-md-12 text-center">
      <div class="bubble"> <!-- Ajout de la classe bubble ici -->
        <h2 class="mb-4">Pourquoi Nous Soutenir?</h2>
        <p>
          AnimauxCherchentMaison.com travaille sans relâche pour sauver et prendre soin des animaux abandonnés. Avec votre aide, nous pouvons continuer notre mission et offrir une seconde chance à ceux qui en ont le plus besoin.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/horses/index.html.erb
<!-- app/views/horses/index.html.erb -->
<div class="container mt-5">
  <h1 class="text-center text-success my-5">Chevaux Disponibles à l'Adoption</h1>
  <p class="no-availability-message">Pas de chevaux disponibles</p>
</div>

app/views/horses/show.html.erb
<h1>Horses#show</h1>
<p>Find me in app/views/horses/show.html.erb</p>

app/views/reptiles/index.html.erb
<!-- app/views/reptiles/index.html.erb -->
<div class="container mt-5">
  <h1 class="text-center text-success my-5">Reptiles Disponibles à l'Adoption</h1>
  <p class="no-availability-message">Pas de reptiles disponibles</p>
</div>

app/views/reptiles/show.html.erb
<h1>Reptiles#show</h1>
<p>Find me in app/views/reptiles/show.html.erb</p>